version: "2"

services:
  frontend:
    image: guitarhorse-frontend
    build:
      context: ./frontend/
    volumes:
      - ./frontend/app/:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: '*'
      VIRTUAL_HOST_WEIGHT: 0
  creator:
    image: guitarhorse-creator
    build:
      context: ./creator/
    volumes:
      - ./creator/app/:/usr/share/nginx/html
    ports:
      - 5556:80
  backend:
    image: guitarhorse-backend
    command: ./docker-compose-start.sh
    build:
      context: ./backend/
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      DB_URI: postgres://postgres:password@postgres:5432/guitarhorse
      VIRTUAL_HOST: '*/api/*'
      VIRTUAL_HOST_WEIGHT: 1
      EXTRA_SETTINGS: 'reqrep ^([^\ :]*)\ /api/(.*) \1\ /\2, reqadd X-Forwarded-Script-Name:\ /api'
  proxy:
    image: dockercloud/haproxy
    links:
      - frontend
      - backend
    ports:
      - 5555:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: guitarhorse
  frontend-builder:
    build:
      context: ./builder
    volumes:
      - ./frontend/src:/build/src
      - ./frontend/app:/build/app
  creator-builder:
    build:
      context: ./builder
    volumes:
      - ./creator/src:/build/src
      - ./creator/app:/build/app
